import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//cambia el titulo de la pagina
export const metadata: Metadata = {
  title: "Ejemplo Clase Bootcamp 3.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <p className="w-full bg-red-600 ">RootLayout</p>
        {children}
        <p className="w-full bg-red-600 ">Footer RootLayout</p>
      </body>
    </html>
  ); 
}
