import { Metadata } from "next";

//cambia el titulo de la pagina bien arriba
export const metadata: Metadata = {
    title: "Dashboard Metadata",
    description: "Generated by create next app",
  };

export default function DashboardLayour({
    children,
}:{
    children: React.ReactNode
}) {    
    return (
        <div>
            <p className= "w-full bg-blue-600"> DashboardLatyout</p>
        {children}
        <p className= "w-full bg-blue-600"> Footer DashboardLatyout</p>
        </div>
        
    )
}